# Site settings
title: Joe Canero
email: caneroj1@tcnj.edu
description: > # this means to ignore newlines until "baseurl:"
  Joe Canero's developer site. Check out his blog and his code samples.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "caneroj1.github.io" # the base hostname & protocol for your site
twitter_username: JCanero
github_username:  caneroj1

# Build settings
markdown: kramdown
highlighter: pygments
